# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle & SonarCloud

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    #- name: Build with Gradle
    #  run: ./gradlew build


    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./gradlew build sonarqube --info

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        release_name: Release ${{ github.ref }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/libs/*
        file_glob: true
        #asset_name: my thing
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"


    #- name: Run test action
    #  uses: itsmeow/curseforge-upload@master
    #  with:
    #    token: ${{ secrets.CF_API_TOKEN }}
    #    project_id: 262222
    #    game_endpoint: minecraft
    #    file_path: test_jar.jar
    #    changelog: Test changelog message!
    #    display_name: Test Jar
    #    game_versions: minecraft-1-12:1.12.2,4458,2:Java 7,Minecraft 1.12:1-12,1.12.1,Forge
    #    release_type: alpha
    #    relations: betteranimalsplus:incompatible,claimit:optionalDependency
